ABCCompanies/ABCCompanies/Models/Company.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ABCCompanies.Models
{
    public class Company
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string Logo { get; set; }
        public ICollection<Employee> Employees { get; set; }
    }
}

ABCCompanies/ABCCompanies/Models/ViewModel/CompanyViewModel.cs
using ABCCompanies.Domain;

namespace ABCCompanies.Models.ViewModel
{
    public class CompanyViewModel
    {

        public CompanyViewModel(Company company)
        {
            Id = company.Id;
            Name = company.Name;
            Email = company.Email;
            Logo = company.Logo;
            WebSite = company.Website;
        }

        public CompanyViewModel()
        {

        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Logo { get; set; }
        public string WebSite { get; set; }
    }
}

ABCCompanies/ABCCompanies/Controllers/CompanyController.cs
using System;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ABCCompanies.Data.Contracts;
using ABCCompanies.Domain;
using ABCCompanies.Infrastructure;
using ABCCompanies.Models.ViewModel;

namespace ABCCompanies.Controllers
{
    [CustomAuthenticationFilter]
    public class CompanyController : BaseController
    {
        public CompanyController(IUnitOfWork unitOfWork) : base(unitOfWork)
        {
        }

        // GET: Company
        [CustomAuthorize("CanRead")]
        public ActionResult Index()
        {
            return View();
        }

        [CustomAuthorize("CanRead")]
        public PartialViewResult GetCompaniesListPartial()
        {
            var companies = UnitOfWork.Companies.GetAll().ToList().Select(c => new CompanyViewModel(c));
            return PartialView("_CompanyList", companies);
        }

        [HttpPost]
        [CustomAuthorize("CanCreate")]
        public ActionResult Add(CompanyViewModel companyViewModel)
        {
            if (companyViewModel == null) {
                throw new InvalidOperationException();
            }

            var newCompany = new Company
            {
                Name = companyViewModel.Name,
                Email = companyViewModel.Email,
                Website = companyViewModel.WebSite
            };
            HttpPostedFileBase postedFile = Request.Files["LogoFile"];
            if (postedFile.FileName != "") {
                newCompany.Logo = UploadFile(postedFile);
            }


            UnitOfWork.Companies.Add(newCompany);
            TempData["Messages"] = UnitOfWork.Save() > 0 ? "Company created successfully." : "Company creation faild. Please try again.";
            return RedirectToAction("Index");
        }

        private string UploadFile(HttpPostedFileBase uploadedFile)
        {
            if (uploadedFile != null) {
                string extension = Path.GetExtension(uploadedFile.FileName);
                if (extension.ToLower() == ".png" || extension.ToLower() == ".jpg") {
                    Stream strm = uploadedFile.InputStream;
                    using (var image = System.Drawing.Image.FromStream(strm)) {
                        int newWidth = 200;
                        int newHeight = 200;
                        var thumbImg = new Bitmap(newWidth, newHeight);
                        var thumbGraph = Graphics.FromImage(thumbImg);
                        thumbGraph.CompositingQuality = CompositingQuality.HighQuality;
                        thumbGraph.SmoothingMode = SmoothingMode.HighQuality;
                        thumbGraph.InterpolationMode = InterpolationMode.HighQualityBicubic;
                        var imgRectangle = new Rectangle(0, 0, newWidth, newHeight);
                        thumbGraph.DrawImage(image, imgRectangle);
                        string relativePath = @"Content\Images\CompanyImages\";
                        string newFileName = Guid.NewGuid() + extension;
                        string targetPath = Server.MapPath(@"~\" + relativePath) + newFileName;
                        thumbImg.Save(targetPath, image.RawFormat);
                        return relativePath + newFileName;
                    }
                }
            }
            return string.Empty;
        }

        [CustomAuthorize("CanUpdate")]
        [HttpGet]
        public PartialViewResult Edit(int id)
        {
            var company = UnitOfWork.Companies.GetById(id);

            if (company == null) {
                throw new Exception("Unable to find selected company.");
            }

            return PartialView("_EditCompany", new CompanyViewModel(company));
        }

        [CustomAuthorize("CanUpdate")]
        [HttpPost]
        public ActionResult Edit(CompanyViewModel companyViewModel)
        {
            if (companyViewModel == null) {
                throw new Exception("Unable to edit company with given details.");
            }

            var company = UnitOfWork.Companies.GetById(companyViewModel.Id);

            company.Name = companyViewModel.Name;
            company.Email = companyViewModel.Email;
            company.Website = companyViewModel.WebSite;


            HttpPostedFileBase postedFile = Request.Files["LogoFile"];

            if (postedFile.FileName != "") {
                company.Logo = UploadFile(postedFile);
            }

            UnitOfWork.Companies.Update(company);
            if (UnitOfWork.Save() > 0)
                TempData["Messages"] = "Company update successfully.";
            else
                TempData["ErrorMessages"] = "Company update faild. Please try again.";
            return RedirectToAction("Index");
        }

        [CustomAuthorize("CanDelete")]
        public ActionResult Delete(int id)
        {
            var company = UnitOfWork.Companies.GetById(id);

            if (company == null) {
                throw new Exception("Unable to find company for delete.");
            }

            if (company.Employees.Count > 0) {
                TempData["ErrorMessages"] = "Unable to delete company. There are number of employee(s) assocites with it.";
                return RedirectToAction("Index");
            }

            UnitOfWork.Companies.Delete(company);
            if (UnitOfWork.Save() > 0)
                TempData["Messages"] = "Company deleted successfully.";
            else
                TempData["ErrorMessages"] = "Company delete faild. Please try again.";
            return RedirectToAction("Index");
        }

    }
}

ABCCompanies/ABCCompanies/Controllers/EmployeeController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using ABCCompanies.Data.Contracts;
using ABCCompanies.Domain;
using ABCCompanies.Infrastructure;
using ABCCompanies.Models.ViewModel;

namespace ABCCompanies.Controllers
{
    [CustomAuthenticationFilter]
    public class EmployeeController : BaseController
    {
        public EmployeeController(IUnitOfWork unitOfWork) : base(unitOfWork)
        {
        }

        // GET: Employee
        [CustomAuthorize("CanRead")]
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        [CustomAuthorize("CanRead")]
        public PartialViewResult GetEmployeesByCompanyId(int companyId)
        {
            var employees = UnitOfWork.Employees.GetAll()
                                                .Where(e => e.Company.Id == companyId)
                                                .ToList()
                                                .Select(e => new EmployeeViewModel(e));
            return PartialView("_EmployeeList", employees);
        }

        [HttpGet]
        [CustomAuthorize("CanRead")]
        public PartialViewResult GetEmployeesListPartial()
        {
            var employees = UnitOfWork.Employees.GetAll().ToList().Select(e => new EmployeeViewModel(e));
            return PartialView("_EmployeeList", employees);
        }


        [HttpGet]
        [CustomAuthorize("CanRead")]
        public PartialViewResult GetAddEmployeePartial(int companyId)
        {
            var companies = UnitOfWork.Companies.GetAll().ToList().Select(e => new CompanyViewModel(e)).ToList();
            var newEmployeeViewModel = new EmployeeViewModel
            {
                Company = companyId != 0 ? new CompanyViewModel(UnitOfWork.Companies.GetById(companyId)) : new CompanyViewModel(),
                AvailableCompanies = companies
            };
            return PartialView("_AddEmployee", newEmployeeViewModel);
        }

        [HttpPost]
        [CustomAuthorize("CanCreate")]
        public ActionResult Add(EmployeeViewModel employeeViewModel)
        {
            if (employeeViewModel == null) {
                throw new InvalidOperationException();
            }
            var newEmployee = new Employee
            {
                FirstName = employeeViewModel.FirstName,
                LastName = employeeViewModel.LastName,
                Email = employeeViewModel.Email,
                Phone = employeeViewModel.Phone,
                Company = UnitOfWork.Companies.GetById(employeeViewModel.Company.Id),
            };

            UnitOfWork.Employees.Add(newEmployee);
            TempData["Messages"] = UnitOfWork.Save() > 0 ? "Employee created successfully" : "Employee creation faild. Please try again";
            return RedirectToAction("Index");
        }

        [CustomAuthorize("CanUpdate")]
        [HttpGet]
        public PartialViewResult Edit(int id)
        {
            var employee = new EmployeeViewModel(UnitOfWork.Employees.GetById(id));

            if (employee == null) {
                throw new Exception("Unable to find selected employee.");
            }

            employee.AvailableCompanies = UnitOfWork.Companies.GetAll().ToList().Select(e => new CompanyViewModel(e)).ToList();

            return PartialView("_EditEmployee", employee);
        }

        [CustomAuthorize("CanUpdate")]
        [HttpPost]
        public ActionResult Edit(EmployeeViewModel employeeViewModel)
        {
            if (employeeViewModel == null) {
                throw new Exception("Unable to edit employee with given details.");
            }

            var employee = UnitOfWork.Employees.GetById(employeeViewModel.Id);

            employee.FirstName = employeeViewModel.FirstName;
            employee.LastName = employeeViewModel.LastName;
            employee.Email = employeeViewModel.Email;
            employee.Phone = employeeViewModel.Phone;
            employee.CompanyId = employeeViewModel.Company.Id;

            UnitOfWork.Employees.Update(employee);
            if (UnitOfWork.Save() > 0)
                TempData["Messages"] = "Employee update successfully.";
            else
                TempData["ErrorMessages"] = "Employee update faild. Please try again.";
            return RedirectToAction("Index");
        }

        [CustomAuthorize("CanDelete")]
        public ActionResult Delete(int id)
        {
            var employee = UnitOfWork.Employees.GetById(id);

            if (employee == null) {
                throw new Exception("Unable to find employee for delete.");
            }

            UnitOfWork.Employees.Delete(employee);
            if (UnitOfWork.Save() > 0)
                TempData["Messages"] = "Employee deleted successfully.";
            else
                TempData["ErrorMessages"] = "Employee delete faild. Please try again.";
            return RedirectToAction("Index");
        }
    }
}

ABCCompanies/ABCCompanies/Views/Company/Index.cshtml
@{
    ViewBag.Title = "Manage Companies";
    Layout = "~/Views/Shared/_Layout.cshtml";    
}

<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">@ViewBag.Title</h1>
</div>

@{
    Html.RenderAction("GetCompaniesListPartial", "Company");
}

ABCCompanies/ABCCompanies/Views/Company/_AddCompany.cshtml
@model ABCCompanies.Models.ViewModel.CompanyViewModel

@using (Html.BeginForm("Add", "Company", FormMethod.Post, new { id = "add-new-company-form", enctype = "multipart/form-data" }))
{
    <div class="form-group">
        <label for="company-name">Name</label>
        @Html.TextBoxFor(model => model.Name, new { @type = "text", @class = "form-control", id = "company-name", required = "required" })
    </div>
    <div class="form-group">
        <label for="company-email">email</label>
        @Html.TextBoxFor(model => model.Email, new { @type = "email", @class = "form-control", id = "company-email", required = "required" })
    </div>
    <div class="form-group">
        <label for="company-web">Web</label>
        @Html.TextBoxFor(model => model.WebSite, new { @type = "text", @class = "form-control", id = "company-email" })
    </div>
    <div class="form-group">
        <label for="company-web">Logo</label>
        <input type="file" name="LogoFile" accept='image/*' />
    </div>
    

    <button type="submit" class="btn btn-primary" @(!User.IsInRole("CanCreate")? "disabled" : null)>Save</button>
    <button type="reset" class="btn btn-warning">Clear</button>
}

ABCCompanies/ABCCompanies/Views/Company/_CompanyList.cshtml
@model IEnumerable<ABCCompanies.Models.ViewModel.CompanyViewModel>

<div class="col-xl-12">
    <div class="card shadow mb-4">
        <!-- Card Header - Dropdown -->
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            <h6 class="m-0 font-weight-bold text-primary">Companies</h6>
            @if (User.IsInRole("CanCreate")) {
                <a href="#" class="btn btn-circle" id="add-new-company-button">
                    <i class="fas fa-plus"></i>
                </a>
            }
            </div>
        <!-- Card Body -->
        <div class="card-body">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th scope="col">Logo</th>
                        <th scope="col">Name</th>
                        <th scope="col">Email</th>
                        <th scope="col">Web</th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model) {
                        <tr class="company-row" data-company-id="@item.Id">
                            <td>
                                <img src="@item.Logo" class="rounded float-left company-image-small" />
                            </td>
                            <td>@item.Name</td>
                            <td>@item.Email</td>
                            <td>@item.WebSite</td>
                            <td>
                                @if (User.IsInRole("CanUpdate")) {
                                    <a href="#" class="btn btn-secondary btn-circle btn-sm edit-company-button">
                                        <i class="fas fa-edit"></i>
                                    </a>
                                }
                                @if (User.IsInRole("CanRead")) {
                                    <a href="#" class="btn btn-primary btn-circle btn-sm show-employees-button">
                                        <i class="fas fa-users"></i>
                                    </a>
                                }
                                @if (User.IsInRole("CanDelete")) {
                                    <a href="@Url.Action("Delete", "Company", new { id = item.Id })" class="btn btn-danger btn-circle btn-sm delete-company-button" 
                                       onclick="return confirm('Are you sure to delete this company?')">
                                        <i class="fas fa-trash"></i>
                                    </a>
                                }
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
<script>
    function showEmployees(companyId) {
        showEmployeeDrawer();
        $.ajax({
            type: "GET",
            url: '@Url.Action("GetEmployeesByCompanyId", "Employee")',
            data: { companyId: companyId },
            contentType: "application/json; charset=utf-8",
            success: function (reponse) {
                $('#employee-drawer').find('.drawer-body').html(reponse);
                $('#employee-list-card').attr('data-company-id', companyId);
            },
            error: function () {
            }
        });
    }
</script>

ABCCompanies/ABCCompanies/Views/Company/_EditCompany.cshtml
@model ABCCompanies.Models.ViewModel.CompanyViewModel

@using (Html.BeginForm("Edit", "Company", FormMethod.Post, new { id = "add-new-company-form", enctype = "multipart/form-data" })) {

    @Html.HiddenFor(model => model.Id);
    <div class="form-group">
        <label for="company-name">Name</label>
        @Html.TextBoxFor(model => model.Name, new { @type = "text", @class = "form-control", id = "company-name", required = "required" })
    </div>
    <div class="form-group">
        <label for="company-email">email</label>
        @Html.TextBoxFor(model => model.Email, new { @type = "email", @class = "form-control", id = "company-email", required = "required" })
    </div>
    <div class="form-group">
        <label for="company-web">Web</label>
        @Html.TextBoxFor(model => model.WebSite, new { @type = "text", @class = "form-control", id = "company-email" })
    </div>
    <div class="form-group">
        <label for="company-web">Logo</label>
        <input type="file" name="LogoFile" accept='image/*' />
    </div>


    <button type="submit" class="btn btn-primary" @(!User.IsInRole("CanCreate") ? "disabled" : null)>Save</button>
    <button type="reset" class="btn btn-warning">Clear</button>
}