ABCCompanies/ABCCompanies/Models/SecurityProfile.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ABCCompanies.Models
{
    public class SecurityProfile
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public bool CanCreate { get; set; }
        public bool CanRead { get; set; }
        public bool CanUpdate { get; set; }
        public bool CanDelete { get; set; }
        public ICollection<User> Users { get; set; }
    }
}

ABCCompanies/ABCCompanies/Models/ViewModel/SecurityProfileViewModel.cs
using ABCCompanies.Domain;

namespace ABCCompanies.Models.ViewModel
{
    public class SecurityProfileViewModel
    {
        public SecurityProfileViewModel()
        {

        }

        public SecurityProfileViewModel(SecurityProfile securityProfile)
        {
            Id = securityProfile.Id;
            Name = securityProfile.Name;
            CanCreate = securityProfile.CanCreate;
            CanRead = securityProfile.CanRead;
            CanUpdate = securityProfile.CanUpdate;
            CanDelete = securityProfile.CanDelete;
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public bool CanCreate { get; set; }
        public bool CanRead { get; set; }
        public bool CanUpdate { get; set; }
        public bool CanDelete { get; set; }

    }
}

ABCCompanies/ABCCompanies/Controllers/SecurityProfileController.cs
using ABCCompanies.Data.Contracts;
using ABCCompanies.Domain;
using ABCCompanies.Infrastructure;
using ABCCompanies.Models.ViewModel;
using System;
using System.Linq;
using System.Web.Mvc;

namespace ABCCompanies.Controllers
{
    [CustomAuthenticationFilter]
    public class SecurityProfileController : BaseController
    {
        public SecurityProfileController(IUnitOfWork unitOfWork) : base(unitOfWork)
        {
        }

        // GET: SecurityProfile
        [CustomAuthorize("CanRead")]
        public ActionResult Index()
        {
            return View();
        }

        [CustomAuthorize("CanRead")]
        public PartialViewResult GetSecurityProfileListPartial()
        {
            var securityProfiles = UnitOfWork.SecurityProfiles.GetAll().ToList().Select(s => new SecurityProfileViewModel(s));
            return PartialView("_SecurityProfileList", securityProfiles);
        }

        [HttpPost]
        [CustomAuthorize("CanCreate")]
        public ActionResult Add(SecurityProfileViewModel securityProfileViewModel)
        {
            if (securityProfileViewModel == null) {
                throw new InvalidOperationException();
            }

            var newSecurityProfile = new SecurityProfile
            {
                Name = securityProfileViewModel.Name,
                CanCreate = securityProfileViewModel.CanCreate,
                CanRead = securityProfileViewModel.CanRead,
                CanUpdate = securityProfileViewModel.CanUpdate,
                CanDelete = securityProfileViewModel.CanDelete
            };

            UnitOfWork.SecurityProfiles.Add(newSecurityProfile);
            TempData["Messages"] = UnitOfWork.Save() > 0 ? "Security profile created successfully" : "Security profile creation faild. Please try again";
            return RedirectToAction("Index");
        }


        [CustomAuthorize("CanUpdate")]
        [HttpGet]
        public PartialViewResult Edit(int id)
        {
            var securityProfile = new SecurityProfileViewModel(UnitOfWork.SecurityProfiles.GetById(id));

            if (securityProfile == null) {
                throw new Exception("Unable to find selected profile.");
            }

            return PartialView("_EditSecurityProfile", securityProfile);
        }

        [CustomAuthorize("CanUpdate")]
        [HttpPost]
        public ActionResult Edit(SecurityProfileViewModel securityProfileViewModel)
        {
            if (securityProfileViewModel == null) {
                throw new Exception("Unable to edit security profile with given details.");
            }

            var profile = UnitOfWork.SecurityProfiles.GetById(securityProfileViewModel.Id);

            profile.Name = securityProfileViewModel.Name;
            profile.CanCreate = securityProfileViewModel.CanCreate;
            profile.CanRead = securityProfileViewModel.CanRead;
            profile.CanUpdate = securityProfileViewModel.CanUpdate;
            profile.CanDelete = securityProfileViewModel.CanDelete;

            UnitOfWork.SecurityProfiles.Update(profile);
            if (UnitOfWork.Save() > 0)
                TempData["Messages"] = "Security profile update successfully.";
            else
                TempData["ErrorMessages"] = "Security profile update faild. Please try again.";
            return RedirectToAction("Index");
        }

        [CustomAuthorize("CanDelete")]
        public ActionResult Delete(int id)
        {
            var profile = UnitOfWork.SecurityProfiles.GetById(id);

            if (profile == null) {
                throw new Exception("Unable to find security profile for delete.");
            }

            if (profile.Users.Count > 0) {
                TempData["ErrorMessages"] = "Unable to delete security profile. There are number of user(s) assocites with it.";
                return RedirectToAction("Index");
            }

            UnitOfWork.SecurityProfiles.Delete(profile);
            if (UnitOfWork.Save() > 0)
                TempData["Messages"] = "security profile deleted successfully.";
            else
                TempData["ErrorMessages"] = "security profile delete faild. Please try again.";
            return RedirectToAction("Index");
        }
    }
}

ABCCompanies/ABCCompanies/Views/SecurityProfile/Index.cshtml
@{
    ViewBag.Title = "Manage Security Profiles";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">@ViewBag.Title</h1>
</div>

@{
    Html.RenderAction("GetSecurityProfileListPartial", "SecurityProfile");
}

ABCCompanies/ABCCompanies/Views/SecurityProfile/_AddSecurityProfile.cshtml
@model ABCCompanies.Models.ViewModel.SecurityProfileViewModel

@using (Html.BeginForm("Add", "SecurityProfile", FormMethod.Post, new { id = "add-new-security-profile-form" })) {
    <div class="form-group">
        <label for="profile-name">Profile Name</label>
        @Html.TextBoxFor(model => model.Name, new { @type = "text", @class = "form-control", id = "profile-name", required = "required" })
    </div>
    <div class="form-group">
        <div class="form-check form-check-inline">
            @Html.CheckBoxFor(model => model.CanCreate, new { @class = "form-check-input", id = "profile-can-create" })
            <label class="form-check-label" for="profile-can-create">Can Create</label>
        </div>
        <div class="form-check form-check-inline">
            @Html.CheckBoxFor(model => model.CanRead, new { @class = "form-check-input", id = "profile-can-read" })
            <label class="form-check-label" for="profile-can-read">Can Read</label>
        </div>
        <div class="form-check form-check-inline">
            @Html.CheckBoxFor(model => model.CanUpdate, new { @class = "form-check-input", id = "profile-can-update" })
            <label class="form-check-label" for="profile-can-update">Can Update</label>
        </div>
        <div class="form-check form-check-inline">
            @Html.CheckBoxFor(model => model.CanDelete, new { @class = "form-check-input", id = "profile-can-delete" })
            <label class="form-check-label" for="profile-can-delete">Can Delete</label>
        </div>
    </div>
    <button type="submit" class="btn btn-primary" @(!User.IsInRole("CanCreate") ? "disabled" : null)>Save</button>
    <button type="reset" class="btn btn-warning">Clear</button>
}

ABCCompanies/ABCCompanies/Views/SecurityProfile/_EditSecurityProfile.cshtml
@model ABCCompanies.Models.ViewModel.SecurityProfileViewModel

@using (Html.BeginForm("Edit", "SecurityProfile", FormMethod.Post, new { id = "add-new-security-profile-form" })) {
    @Html.HiddenFor(model => model.Id)
    <div class="form-group">
        <label for="profile-name">Profile Name</label>
        @Html.TextBoxFor(model => model.Name, new { @type = "text", @class = "form-control", id = "profile-name", required = "required" })
    </div>
    <div class="form-group">
        <div class="form-check form-check-inline">
            @Html.CheckBoxFor(model => model.CanCreate, new { @class = "form-check-input", id = "profile-can-create" })
            <label class="form-check-label" for="profile-can-create">Can Create</label>
        </div>
        <div class="form-check form-check-inline">
            @Html.CheckBoxFor(model => model.CanRead, new { @class = "form-check-input", id = "profile-can-read" })
            <label class="form-check-label" for="profile-can-read">Can Read</label>
        </div>
        <div class="form-check form-check-inline">
            @Html.CheckBoxFor(model => model.CanUpdate, new { @class = "form-check-input", id = "profile-can-update" })
            <label class="form-check-label" for="profile-can-update">Can Update</label>
        </div>
        <div class="form-check form-check-inline">
            @Html.CheckBoxFor(model => model.CanDelete, new { @class = "form-check-input", id = "profile-can-delete" })
            <label class="form-check-label" for="profile-can-delete">Can Delete</label>
        </div>
    </div>
    <button type="submit" class="btn btn-primary" @(!User.IsInRole("CanCreate") ? "disabled" : null)>Save</button>
    <button type="reset" class="btn btn-warning">Clear</button>
}

ABCCompanies/ABCCompanies/Views/SecurityProfile/_SecurityProfileList.cshtml
@model IEnumerable<ABCCompanies.Models.ViewModel.SecurityProfileViewModel>

<div class="col-xl-12">
    <div class="card shadow mb-4">
        <!-- Card Header - Dropdown -->
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            <h6 class="m-0 font-weight-bold text-primary">Security Profiles</h6>
            @if (User.IsInRole("CanCreate")) {
                <a href="#" class="btn btn-circle" id="add-security-profile-button">
                    <i class="fas fa-plus"></i>
                </a>
            }
        </div>
        <!-- Card Body -->
        <div class="card-body">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th scope="col">Name</th>
                        <th scope="col">Can Create</th>
                        <th scope="col">Can Read</th>
                        <th scope="col">Can Update</th>
                        <th scope="col">Can Delete</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model) {
                    <tr class="security-profile-row" data-security-profile-id="@item.Id">
                        <td>@item.Name</td>
                        <td><i class="fas @(item.CanCreate? "text-success fa-check-circle" : "text-danger fa-minus-circle")"></i></td>
                        <td><i class="fas @(item.CanRead? "text-success fa-check-circle" : "text-danger fa-minus-circle")"></i></td>
                        <td><i class="fas @(item.CanUpdate? "text-success fa-check-circle" : "text-danger fa-minus-circle")"></i></td>
                        <td><i class="fas @(item.CanDelete? "text-success fa-check-circle" : "text-danger fa-minus-circle")"></i></td>
                        <td>
                            @if (User.IsInRole("CanUpdate")) {
                                <a href="#" class="btn btn-secondary btn-circle btn-sm edit-security-profile-button">
                                    <i class="fas fa-edit"></i>
                                </a>
                            }
                            @if (User.IsInRole("CanDelete")) {
                                <a href="@Url.Action("Delete", "SecurityProfile", new { id = item.Id })" class="btn btn-danger btn-circle btn-sm delete-security-profile-button"
                                   onclick="return confirm('Are you sure to security profile this company?')"> 
                                    <i class="fas fa-trash"></i>
                                </a>
                            }
                        </td>
                    </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>